import { z } from "zod";

export const schemas = {
  create_client: z.object({
    name: z.string().min(2),
    phone: z.string().min(6),
    address: z.string().min(5),
    email: z.string().email().optional(),
    notes: z.string().optional(),
  }),
  schedule_visit: z.object({
    client_id: z.string().uuid().optional(),
    client_name: z.string().min(2).optional(),
    service_name: z.string().min(2).optional(),
    title: z.string().min(2).optional(),
    description: z.string().optional(),
    scheduled_date: z.string().min(10),
    duration_minutes: z.number().int().positive().optional(),
  }),
  create_budget: z.object({
    client_id: z.string().uuid().optional(),
    client_name: z.string().min(2).optional(),
    title: z.string().min(2),
    description: z.string().optional(),
    total_amount: z.number().positive(),
    valid_until: z.string().optional(),
  }),
  update_budget_status: z.object({
    budget_id: z.string().uuid().optional(),
    title: z.string().optional(),
    client_name: z.string().optional(),
    status: z.enum(["pending", "approved", "rejected"]),
  }),
  update_stock: z.object({
    product_id: z.string().uuid().optional(),
    product_name: z.string().min(2).optional(),
    type: z.enum(["in", "out"]),
    quantity: z.number().positive(),
    unit_cost: z.number().positive().optional(),
    movement_date: z.string().optional(),
    description: z.string().optional(),
    appointment_id: z.string().uuid().optional(),
  }),
  approve_budget_and_record_income: z.object({
    client_id: z.string().uuid().optional(),
    client_name: z.string().min(2).optional(),
    appointment_id: z.string().uuid().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    total_amount: z.number().positive(),
    due_date: z.string().optional(),
    status: z.enum(["paid", "pending"]).optional(),
  }),
  record_service_income: z.object({
    client_id: z.string().uuid().optional(),
    client_name: z.string().min(2).optional(),
    service_name: z.string().min(2).optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    total_amount: z.number().positive().optional(),
    due_date: z.string().optional(),
    status: z.enum(["paid", "pending"]).optional(),
  }),
  record_income: z.object({
    amount: z.number().positive(),
    title: z.string().optional(),
    description: z.string().optional(),
    transaction_date: z.string().optional(),
    client_id: z.string().uuid().optional(),
    category_id: z.string().uuid().optional(),
  }),
  record_expense: z.object({
    amount: z.number().positive(),
    category_name: z.string().min(2).optional(),
    parent_category_name: z.string().min(2).optional(),
    description: z.string().optional(),
    transaction_date: z.string().optional(),
    status: z.enum(["paid", "pending"]).optional(),
    due_date: z.string().optional(),
  }),
  record_inventory_purchase: z.object({
    product_id: z.string().uuid().optional(),
    product_name: z.string().min(2).optional(),
    quantity: z.number().positive().optional(),
    unit_cost: z.number().positive().optional(),
    movement_date: z.string().optional(),
    description: z.string().optional(),
    also_record_expense: z.boolean().optional(),
  }),
  record_partner_commission: z.object({
    partner_name: z.string().min(2),
    percent: z.number().positive().max(1).optional(),
    amount: z.number().positive().optional(),
    movement_id: z.string().uuid().optional(),
    credit_type: z.enum(["cash", "insumos"]).optional(),
    description: z.string().optional(),
  }),
  create_note: z.object({
    title: z.string().optional(),
    content: z.string().min(1),
    importance: z.enum(["low", "medium", "high"]).optional(),
    tags: z.array(z.string()).optional(),
    client_name: z.string().optional(),
    appointment_id: z.string().uuid().optional(),
  }),
  create_task: z.object({
    title: z.string().optional(),
    description: z.string().optional(),
    importance: z.enum(["low", "medium", "high"]).optional(),
    tags: z.array(z.string()).optional(),
    due_date: z.string().optional(),
    client_name: z.string().optional(),
    status: z.enum(["open", "in_progress", "done"]).optional(),
  }),
  create_maintenance_plan: z.object({
    client_id: z.string().uuid().optional(),
    client_name: z.string().optional(),
    service_name: z.string().optional(),
    title: z.string().min(2),
    default_labor_cost: z.number().nonnegative().optional(),
    materials_markup_pct: z.number().min(0).max(100).optional(),
    preferred_weekday: z.number().int().min(0).max(6).optional(),
    preferred_week_of_month: z.number().int().min(1).max(4).optional(),
    window_days: z.number().int().positive().optional(),
    billing_day: z.number().int().min(1).max(31).optional(),
    status: z.enum(["active", "paused"]).optional(),
  }),
  generate_monthly_task: z.object({
    plan_id: z.string().uuid().optional(),
    client_name: z.string().optional(),
    cycle: z.string().optional(),
  }),
  close_monthly_execution: z.object({
    plan_id: z.string().uuid().optional(),
    execution_id: z.string().uuid().optional(),
    client_name: z.string().optional(),
    title: z.string().optional(),
    description: z.string().optional(),
    labor_cost: z.number().nonnegative().optional(),
    materials_total: z.number().nonnegative().optional(),
    status: z.enum(["paid", "pending"]).optional(),
    due_date: z.string().optional(),
  }),
} as const;

export type IntentKey = keyof typeof schemas;
export type IntentParams<K extends IntentKey> = z.infer<(typeof schemas)[K]>;
